//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGBtoRALv7_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RGBtoRALv7_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] big_sip_line {
            get {
                object obj = ResourceManager.GetObject("big_sip_line", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ColorCollection CollectionName=&quot;Classic&quot; HaveTypeDesc=&quot;true&quot;&gt;
        ///  &lt;Color Name=&quot;RAL 1000&quot;&gt;
        ///    &lt;Description ru=&quot;Зелёно-бежевый&quot; en=&quot;Green beige&quot; /&gt;
        ///    &lt;CMYKC&gt; 10  10  50  10&lt;/CMYKC&gt;
        ///    &lt;CMYKU&gt;  0   3  40  10&lt;/CMYKU&gt;
        ///    &lt;HEX&gt;#CCC58F&lt;/HEX&gt;
        ///    &lt;RGB R=&quot;204&quot; G=&quot;197&quot; B=&quot;143&quot; /&gt;
        ///  &lt;/Color&gt;
        ///  &lt;Color Name=&quot;RAL 1001&quot;&gt;
        ///    &lt;Description ru=&quot;Бежевый&quot; en=&quot;Beige&quot; /&gt;
        ///    &lt;CMYKC&gt;  0  20  50  20&lt;/CMYKC&gt;
        ///    &lt;CMYKU&gt; 10  20  40   0&lt;/CMYKU&gt;
        ///    &lt;HEX&gt;#D1BC8A&lt;/HEX&gt;
        ///    &lt;RGB R=&quot;209&quot; G=&quot;188&quot; B=&quot;138&quot; /&gt;
        ///  &lt;/Color&gt;
        ///  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] closeBlue {
            get {
                object obj = ResourceManager.GetObject("closeBlue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] closeWhite {
            get {
                object obj = ResourceManager.GetObject("closeWhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ColorCollection CollectionName=&quot;Design&quot; HaveTypeDesc=&quot;false&quot;&gt;
        ///  &lt;Color Name=&quot;RAL 000 15 00&quot;&gt;
        ///    &lt;CMYKC&gt; 73  61  56  66&lt;/CMYKC&gt;
        ///    &lt;CMYKU&gt; 76  60  44  69&lt;/CMYKU&gt;
        ///    &lt;HEX&gt;#2E3032&lt;/HEX&gt;
        ///    &lt;RGB R=&quot;46&quot; G=&quot;48&quot; B=&quot;50&quot; /&gt;
        ///  &lt;/Color&gt;
        ///  &lt;Color Name=&quot;RAL 000 20 00&quot;&gt;
        ///    &lt;CMYKC&gt; 70  58  53  60&lt;/CMYKC&gt;
        ///    &lt;CMYKU&gt; 72  57  44  62&lt;/CMYKU&gt;
        ///    &lt;HEX&gt;#37393B&lt;/HEX&gt;
        ///    &lt;RGB R=&quot;55&quot; G=&quot;57&quot; B=&quot;59&quot; /&gt;
        ///  &lt;/Color&gt;
        ///  &lt;Color Name=&quot;RAL 000 25 00&quot;&gt;
        ///    &lt;CMYKC&gt; 67  55  51  53&lt;/CMYKC&gt;
        ///    &lt;CMYKU&gt; 67  54  43  55&lt;/CMYK [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] downBlue {
            get {
                object obj = ResourceManager.GetObject("downBlue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] downWhite {
            get {
                object obj = ResourceManager.GetObject("downWhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drag_move_2_line {
            get {
                object obj = ResourceManager.GetObject("drag_move_2_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drag_move_2_line_white {
            get {
                object obj = ResourceManager.GetObject("drag_move_2_line_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ColorCollection CollectionName=&quot;Effect&quot; HaveTypeDesc=&quot;false&quot;&gt;
        ///  &lt;Color Name=&quot;RAL 110-1&quot;&gt;
        ///    &lt;CMYKC&gt;  0   0   0   4&lt;/CMYKC&gt;
        ///    &lt;CMYKU&gt;  0   0   3   3&lt;/CMYKU&gt;
        ///    &lt;HEX&gt;#E6EBEB&lt;/HEX&gt;
        ///    &lt;RGB R=&quot;230&quot; G=&quot;235&quot; B=&quot;235&quot; /&gt;
        ///  &lt;/Color&gt;
        ///  &lt;Color Name=&quot;RAL 110-2&quot;&gt;
        ///    &lt;CMYKC&gt;  0   0   8  10&lt;/CMYKC&gt;
        ///    &lt;CMYKU&gt;  3   3   5   0&lt;/CMYKU&gt;
        ///    &lt;HEX&gt;#E0E1D9&lt;/HEX&gt;
        ///    &lt;RGB R=&quot;224&quot; G=&quot;225&quot; B=&quot;217&quot; /&gt;
        ///  &lt;/Color&gt;
        ///  &lt;Color Name=&quot;RAL 110-3&quot;&gt;
        ///    &lt;CMYKC&gt;  7   6  20  15&lt;/CMYKC&gt;
        ///    &lt;CMYKU&gt;  5   5   5  10&lt;/CMYKU&gt;
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string eng_sip_info {
            get {
                return ResourceManager.GetString("eng_sip_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Langs&gt;
        ///  &lt;Lang id=&quot;en&quot;&gt;
        ///    &lt;!--SETTINGS WINDOW--&gt;
        ///    &lt;field_language&gt;Language:&lt;/field_language&gt;
        ///    &lt;field_siptype&gt;Sip type:&lt;/field_siptype&gt;
        ///    &lt;field_siptype_0&gt;All screens&lt;/field_siptype_0&gt;
        ///    &lt;field_siptype_1&gt;Ask for screen&lt;/field_siptype_1&gt;
        ///    &lt;field_siptype_2&gt;Active screen&lt;/field_siptype_2&gt;
        ///    &lt;field_hide_window&gt;Hide main window&lt;/field_hide_window&gt;
        ///    &lt;field_developed&gt;Developed by stormtrooper_34 2020&lt;/field_developed&gt;
        ///    &lt;field_setdefault&gt;Set to Default:&lt;/field_setdefault&gt;
        ///    &lt;fiel [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Langs {
            get {
                return ResourceManager.GetString("Langs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] palette_line {
            get {
                object obj = ResourceManager.GetObject("palette_line", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] palette_line_blue {
            get {
                object obj = ResourceManager.GetObject("palette_line_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] pantone {
            get {
                object obj = ResourceManager.GetObject("pantone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] pushpin_2_fill {
            get {
                object obj = ResourceManager.GetObject("pushpin_2_fill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] pushpin_2_fill_blue {
            get {
                object obj = ResourceManager.GetObject("pushpin_2_fill_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] pushpin_fill {
            get {
                object obj = ResourceManager.GetObject("pushpin_fill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] pushpin_fill_blue {
            get {
                object obj = ResourceManager.GetObject("pushpin_fill_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Roboto_Medium {
            get {
                object obj = ResourceManager.GetObject("Roboto_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ru_sip_info {
            get {
                return ResourceManager.GetString("ru_sip_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] search_line {
            get {
                object obj = ResourceManager.GetObject("search_line", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] search_line_blue {
            get {
                object obj = ResourceManager.GetObject("search_line_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] settings_3_line {
            get {
                object obj = ResourceManager.GetObject("settings_3_line", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] settings_3_line_blue {
            get {
                object obj = ResourceManager.GetObject("settings_3_line_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] sip_line {
            get {
                object obj = ResourceManager.GetObject("sip_line", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] sip_line_blue {
            get {
                object obj = ResourceManager.GetObject("sip_line_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
